import { Routes } from '@angular/router';
import { LoginComponent } from './core/pages/login/login.component';
import { AtenderTurnoComponent } from './shared/pages/atender-turno/atender-turno.component';
import { AusentismosComponent } from './shared/pages/ausentismos/ausentismos.component';
import { CambiarContrasenaComponent } from './shared/pages/cambiar-contrasena/cambiar-contrasena.component';
import { ContratacionComponent } from './shared/pages/contratacion/contratacion.component';
import { DesprendiblesPagoComponent } from './shared/pages/desprendibles-pago/desprendibles-pago.component';
import { EstadisticasAuditoriaComponent } from './shared/pages/estadisticas-auditoria/estadisticas-auditoria.component';
import { EstadisticasTurneroComponent } from './shared/pages/estadisticas-turnero/estadisticas-turnero.component';
import { FormaPagoComponent } from './shared/pages/forma-pago/forma-pago.component';
import { HomeComponent } from './shared/pages/home/home.component';
import { PublicidadComponent } from './shared/pages/publicidad/publicidad.component';
import { ReporteContratacionComponent } from './shared/pages/reporte-contratacion/reporte-contratacion.component';
import { SeguimientoAuditoriaComponent } from './shared/pages/seguimiento-auditoria/seguimiento-auditoria.component';
import { SeleccionComponent } from './shared/pages/seleccion/seleccion.component';
import { SolicitarTurnoComponent } from './shared/pages/solicitar-turno/solicitar-turno.component';
import { VacantesComponent } from './shared/pages/vacantes/vacantes.component';
import { VisualizarTurnosComponent } from './shared/pages/visualizar-turnos/visualizar-turnos.component';
import { AuditoriaComponent } from './shared/pages/auditoria/auditoria.component';
import { FormularioIncapacidadComponent } from './shared/pages/formulario-incapacidad/formulario-incapacidad.component';
import { BuscarIncapacidadComponent } from './shared/pages/buscar-incapacidad/buscar-incapacidad.component';
import { FormularioReporteComponent } from './shared/pages/formulario-reporte/formulario-reporte.component';
import { VistaTotalIncapacidadesComponent } from './shared/pages/vista-total-incapacidades/vista-total-incapacidades.component';
import { SubidaArchivosIncapacidadesComponent } from './shared/pages/subida-archivos-incapacidades/subida-archivos-incapacidades.component';
import { DocumentosContratacionComponent } from './shared/pages/documentos-contratacion/documentos-contratacion.component';
import { VerReporteComponent } from './shared/pages/ver-reporte/ver-reporte.component';
import { ReporteVetadoComponent } from './shared/pages/reporte-vetado/reporte-vetado.component';
import { VetadosGerenciaComponent } from './shared/pages/vetados-gerencia/vetados-gerencia.component';
import { SeguimientoAuditoriaArchivoComponent } from './shared/pages/seguimiento-auditoria-archivo/seguimiento-auditoria-archivo.component';
import { ConsultaFormularioComponent } from './shared/pages/consulta-formulario/consulta-formulario.component';
import { AntecedentesRobotsComponent } from './shared/pages/antecedentes-robots/antecedentes-robots.component';
import { GenerarDocumentosComponent } from './shared/pages/generar-documentos/generar-documentos.component';
import { EnvioPaqueteDocumentacionComponent } from './shared/pages/envio-paquete-documentacion/envio-paquete-documentacion.component';
import { RecibirPaqueteDocumentacionComponent } from './shared/pages/recibir-paquete-documentacion/recibir-paquete-documentacion.component';
import { CrearEstructuraDocumentalComponent } from './features/gestion-documental/pages/crear-estructura-documental/crear-estructura-documental.component';
import { BuscarDocumentacionComponent } from './features/gestion-documental/pages/buscar-documentacion/buscar-documentacion.component';
import { SubirDocumentacionComponent } from './features/gestion-documental/pages/subir-documentacion/subir-documentacion.component';
import { VacanteComponent } from './features/vacante/pages/vacante/vacante.component';
import { PersonalAdministrativoComponent } from './features/personal_administrativos/pages/personal-administrativo/personal-administrativo.component';
import { GestionarPermisosComponent } from './features/gestion-documental/pages/gestionar-permisos/gestionar-permisos.component';
import { ActivosComponent } from './shared/pages/activos/activos.component';

export const routes: Routes = [
  { path: '', component: LoginComponent },
  { path: 'atender-turno', component: AtenderTurnoComponent },
  { path: 'ausentismos', component: AusentismosComponent },
  { path: 'cambiar-contrasena', component: CambiarContrasenaComponent },
  { path: 'contratacion', component: ContratacionComponent },
  { path: 'desprendibles-pago', component: DesprendiblesPagoComponent },
  { path: 'estadisticas-auditoria', component: EstadisticasAuditoriaComponent },
  { path: 'estadisticas-turnero', component: EstadisticasTurneroComponent },
  { path: 'forma-pago', component: FormaPagoComponent },
  { path: 'home', component: HomeComponent },
  { path: 'publicidad', component: PublicidadComponent },
  { path: 'reporte-contratacion', component: ReporteContratacionComponent },
  { path: 'seguimiento-auditoria', component: SeguimientoAuditoriaComponent },
  { path: 'seleccion', component: SeleccionComponent },
  { path: 'solicitar-turno', component: SolicitarTurnoComponent },
  { path: 'vacantes', component: VacantesComponent },
  { path: 'visualizar-turnos', component: VisualizarTurnosComponent },

  { path: 'crear-estructura-documental', component: CrearEstructuraDocumentalComponent },
  { path: 'buscar-documentacion', component: BuscarDocumentacionComponent },
  { path: 'auditoria', component: AuditoriaComponent },
  { path: 'subir-documentacion', component: SubirDocumentacionComponent },
  
  { path: 'envio-paquete-documentacion', component: EnvioPaqueteDocumentacionComponent },
  { path: 'recibir-paquete-documentacion', component: RecibirPaqueteDocumentacionComponent },

  { path: 'subir-documentacion', component: SubirDocumentacionComponent },
  { path: 'formulario-incapacicades', component: FormularioIncapacidadComponent },
  { path: 'busqueda-incapacidades', component: BuscarIncapacidadComponent },
  { path: 'incapacidades-totales', component: VistaTotalIncapacidadesComponent },
  { path: 'formulario-reporte/:cedula', component: FormularioReporteComponent },
  { path: 'subida-archivos-incapacidades', component: SubidaArchivosIncapacidadesComponent },

  { path: 'archivos-contratacion', component: DocumentosContratacionComponent },
  { path: 'ver-reporte', component: VerReporteComponent },
  { path: 'reporte-vetado', component: ReporteVetadoComponent },
  { path: 'vetados-gerencia', component: VetadosGerenciaComponent },
  { path: 'seguimiento-auditoria-archivo', component: SeguimientoAuditoriaArchivoComponent },
  { path: 'consulta-formulario', component: ConsultaFormularioComponent },
  { path: 'antecedentes-robots', component: AntecedentesRobotsComponent },
  { path: 'generar-documentos', component: GenerarDocumentosComponent },

  { path: 'vacante-documentos', component: VacanteComponent },
  { path: 'personal-administrativo', component: PersonalAdministrativoComponent },
  { path: 'gestionar-permisos', component: GestionarPermisosComponent },
  { path: 'activos', component: ActivosComponent }

];
